const exporess = require("express");
const authRoutes = require("./Authentication/authRoutes");
const adminRoutes = require("./Admin/adminRoutes");
const usersRoutes = require("./Users/userRoutes");
const profileRoutes = require("./profile/profileRoutes");
const kualifikasiRoutes = require("./kualifikasi/kualifikasiRoutes");
const kompetensiRoutes = require("./kompetensi/kompetensiRoutes");
const kolabExtRoutes = require("./kolaborator-external/kolabExternalRoutes");
const penunjangRoutes = require("./penunjang/penunjangRoutes");
const ipMhsRoutes = require("./pelaks-pendidikan/ipMhsRoutes");
const bimbinganRoutes = require("./pelaks-pendidikan/bimbinganRoutes");
const bahanAjarRoutes = require("./pelaks-pendidikan/bahanAjarRoutes");
const penelitianRoutes = require("./pelaks-penelitian/penelitianRoutes");
const publikasiKaryaRoutes = require("./pelaks-penelitian/publikasiKaryaRoutes");
const hkiRoutes = require("./pelaks-penelitian/hkiRoutes");
const pengabdianRoutes = require("./pelaks-pengabdian/pengabdianRoutes");
const pembicaraRoutes = require("./pelaks-pengabdian/pembicaraRoutes");
const rekomendasiRoutes = require("./rekomendasi/rekomendasiRoutes");
const kategoriRoutes = require("./kategori/kategoriRoutes");
const dashboardRoutes = require("./dashboard/dashboardRoutes");
const beritaRoutes = require("./Admin/beritaRoutes");
const achievmentsRoutes = require("./Admin/achievementsRoutes");
const absensiRoutes = require("./absensi/absensiRoutes");
const jadwalRapatRoutes = require("./jadwal-rapat/jadwalRapatRoutes");
const helpRoutes = require("./helperRoutes");
const skpiRoutes = require("./skpi/skpiRoutes");
const votingRoutes = require("./e-voting/eVotingRoutes");
const bimbinganAkademikRoutes = require("./bimbingan/bimbinganAkademik");
const tugasAkhirRoutes = require("./bimbingan/tugasAkhirRoutes");
const progresTugasAkhirRoutes = require("./bimbingan/bimbinganTugasAkhirRoutes");
const validasiRoutes = require("./validasi/validasiRoutes");
const laporanRoutes = require("./laporan/laporanRoutes");
const ruanganRoutes = require("./ruangan/ruanganRoutes");
const ujianRoutes = require("./ujian/ujianRoutes");
const cbtRoutes = require("./Authentication/cbtRoutes");
const siakRoutes = require("./siak/siakRoute");
// const parentsRoutes = require("./parents/parentsRoutes");
const absensiExternalRoutes = require("./absensi-external/indexRouter");
const suratRoutes = require("./persuratan/surat");
const router = exporess.Router();

router.use("/auth", authRoutes);
router.use("/admin", adminRoutes);
router.use("/cbt", cbtRoutes);
router.use("/users", usersRoutes);
router.use("/profile", profileRoutes);
router.use("/kualifikasi", kualifikasiRoutes);
router.use("/kompetensi", kompetensiRoutes);
router.use("/penunjang", penunjangRoutes);
router.use("/kolabExt", kolabExtRoutes);
router.use("/ipMhs", ipMhsRoutes);
router.use("/pendidikan/bimbingan", bimbinganRoutes);
router.use("/pendidikan/bahan-ajar", bahanAjarRoutes);
router.use("/penelitian", penelitianRoutes);
router.use("/penelitian/publikasi-karya", publikasiKaryaRoutes);
router.use("/penelitian/hki", hkiRoutes);
router.use("/pengabdian", pengabdianRoutes);
router.use("/pengabdian/pembicara", pembicaraRoutes);
router.use("/rekomendasi", rekomendasiRoutes);
router.use("/kategori", kategoriRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/berita", beritaRoutes);
router.use("/absensi", absensiRoutes);
router.use("/meet", jadwalRapatRoutes);
router.use("/achievments", achievmentsRoutes);
router.use("/skpi", skpiRoutes);
router.use("/voting", votingRoutes);
router.use("/validasi", validasiRoutes);
router.use("/bimbingan-akademik", bimbinganAkademikRoutes);
router.use("/tugas-akhir", tugasAkhirRoutes);
router.use("/progres-tugas-akhir", progresTugasAkhirRoutes);
router.use("/laporan", laporanRoutes);
router.use("/ruangan", ruanganRoutes);
router.use("/ujian", ujianRoutes);
router.use("/siak", siakRoutes);
// router.use("/parents", parentsRoutes);
router.use("/absensi-external", absensiExternalRoutes);
router.use("/surat", suratRoutes);

router.use("/help", helpRoutes);
router.get("/", (req, res) => {
  res.send("Oooopss, route not found!");
});

module.exports = router;
